/**
 * Full tag vocabulary from The Trivia API (https://the-trivia-api.com/v2/tags),
 * normalized the same way user input is (lowercased, spaces/hyphens collapsed
 * to underscores) and deduplicated. Snapshotted 2026-07-06 -- refresh by
 * re-fetching that endpoint if The Trivia API adds new tags.
 *
 * This is the full set a tag can be matched against; THE_TRIVIA_TAGS in
 * catalog.ts remains the much smaller curated subset that maps a tag onto
 * one specific bot category (used to narrow API requests). Tags here that
 * aren't in that curated set have no single owning bot category, but are
 * still valid exact and fuzzy matches -- e.g. for /play tag:culture, or so
 * they surface correctly in /categories search instead of being reported
 * as unrecognized.
 */
export const THE_TRIVIA_TAG_VOCABULARY: string[] = [
  "00s", "1000s", "1300s", "1400s", "1500s", "1600s", "1700s", "1800s",
  "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s",
  "1980s", "1990s", "2000s", "2010s", "2022", "20th_century", "abba", "abbreviations",
  "abolition", "academy_awards", "acronyms", "acting", "action", "actors", "advertising", "africa",
  "agile_methodologies", "aging", "agriculture", "ai", "air_force_one", "airlines", "airports", "alaska",
  "albania", "album_artwork", "alcohol", "algeria", "alliances", "alphabet", "american_civil_war", "american_football",
  "american_revolution", "american_west", "amusement_parks", "anatomy", "ancient", "ancient_civilizations", "ancient_egypt", "ancient_greece",
  "ancient_history", "andorra", "angola", "animals", "antarctica", "anthropology", "antigua_and_barbuda", "archaeology",
  "architecture", "arctic", "argentina", "arithmetic", "armenia", "arms", "art", "arthurian",
  "artists", "arts_and_literature", "asia", "assassinations", "astrology", "astronomy", "astrophysics", "athletes",
  "athletics", "atoms", "australia", "austria", "authors", "aviation", "awards", "aztecs",
  "babies", "bahrain", "baking", "ballet", "baltimore", "bands", "bangladesh", "banking",
  "barbados", "barbeque", "barcelona", "baseball", "basketball", "batman", "battles", "bays",
  "beauty", "beer", "beijing", "belgium", "belize", "benin", "berlin", "beverages",
  "bhutan", "bible", "billiards", "binary", "biography", "biology", "birds", "board_games",
  "boats", "bob_dylan", "bodies_of_water", "bolivia", "bones", "books", "borders", "boston",
  "botany", "botswana", "boxing", "brands", "brazil", "bread", "breakfast", "bridges",
  "britain", "british_history", "british_monarchy", "british_prime_ministers", "brunei", "buddhism", "building", "buildings",
  "bulgaria", "burkina_faso", "burundi", "business", "cakes", "california", "cambodia", "cameroon",
  "canada", "canals", "candy", "cape_verde", "capital_cities", "card_games", "caribbean", "cars",
  "cartoons", "casinos", "castles", "cats", "celebrations", "celtic", "censorship", "central_african_republic",
  "central_america", "ceramics", "chad", "champions", "characters", "charities", "charles_dickens", "cheese",
  "chemical_elements", "chemistry", "chess", "chicago", "childbirth", "childrens_literature", "childrens_tv", "chile",
  "china", "chocolate", "christianity", "christmas", "christopher_columbus", "cities", "city_of_westminster", "civil_engineering",
  "civil_rights", "classic_novels", "classical", "classical_music", "classics", "climate", "climbing", "clothing",
  "cocktails", "coffee", "cold_war", "collective_nouns", "college", "colleges", "colombia", "colonialism",
  "colour", "colours", "comedy", "comics", "communication", "communism", "comoros", "companies",
  "composer", "composers", "computer_science", "computing", "conquest", "consumer_products", "continents", "controversies",
  "cooking", "countries", "country_music", "cover_song", "cricket", "crime", "croatia", "cryptography",
  "cuba", "cubism", "cuisine", "cult_films", "culture", "currency", "cycling", "cyprus",
  "dairy", "dallas", "dance", "darts", "dates", "dc", "decades", "decathlon",
  "democratic_republic_of_the_congo", "demography", "demonyms", "denmark", "dentistry", "deserts", "designers", "desserts",
  "dictators", "dinosaurs", "directors", "disasters", "disease", "diseases", "disney", "djibouti",
  "dogs", "dominica", "dominican_republic", "drama", "drink", "drinking", "drinks", "driving",
  "drugs", "duels", "earth", "earthquakes", "east_timor", "economics", "economy", "ecuador",
  "education", "egypt", "el_salvador", "elections", "electronics", "elements", "elvis_presley", "empires",
  "endocrinology", "engineering", "england", "entertainment", "environment", "epidemiology", "equatorial_guinea", "eritrea",
  "espionage", "eswatini", "etymology", "europe", "events", "exercise", "exploration", "explorers",
  "exports", "fabric", "fairy_tales", "fantasy", "farms", "fashion", "fast_food", "federated_states_of_micronesia",
  "feminism", "festivals", "fiction", "fictitious_characters", "fiji", "film", "film_and_tv", "film_quotes",
  "films", "finance", "first_lines", "firsts", "fish", "fishing", "fitness", "flags",
  "flavors", "florence", "florida", "flowers", "food", "food_and_drink", "football", "formula_1",
  "france", "french", "french_new_wave", "friends", "fruit", "furniture", "gabon", "gambling",
  "games", "gameshows", "gardening", "gases", "general_knowledge", "genetics", "genres", "geography",
  "geology", "geometry", "georgia", "germany", "golf", "gothic", "government", "grains",
  "grammar", "greece", "grenada", "guatemala", "guinea_bissau", "guyana", "gymnastics", "hair",
  "haiti", "halloween", "harry_potter", "hats", "hawaii", "health", "healthcare", "hebrew",
  "herbs", "hg_wells", "hinduism", "hip_hop", "history", "hock", "hockey", "holidays",
  "hollywood", "holy_roman_empire", "horror", "horse_racing", "horses", "human_body", "hungary", "hunting",
  "husky", "idioms", "india", "indigenous_people", "indonesia", "infrastructure", "ingredients", "initials",
  "insects", "instrument", "intelligence", "inventions", "inventors", "iran", "iraq", "ireland",
  "islam", "islands", "israel", "istanbul", "italian_cuisine", "italy", "ivory_coast", "james_bond",
  "japan", "jazz", "jewelry", "jordan", "judaism", "julius_caesar", "kansas", "kazakhstan",
  "kentucky", "kingdom_of_denmark", "kingdom_of_the_netherlands", "kings", "kiribati", "kpop", "kuwait", "kyrgyzstan",
  "lakes", "landmark", "landmarks", "language", "languages", "laos", "las_vegas", "latin",
  "latvia", "law", "leaders", "leadership", "lebanon", "legends", "lesotho", "lgbtq",
  "liberia", "libya", "liechtenstein", "lifestyle", "linguistics", "liquor", "literature", "liverpool",
  "logos", "london", "lord_of_the_rings", "los_angeles", "louisiana", "love", "lyrics", "madagascar",
  "madrid", "malawi", "malaysia", "maldives", "malta", "manchester", "manufacturing", "maps",
  "mardi_gras", "marilyn_monroe", "marine_life", "maritime", "marketing", "maroon_5", "marriage", "marshall_islands",
  "marsupials", "martial_arts", "marvel", "mascots", "massachusetts", "materials", "math", "mathematics",
  "mauritius", "mcu", "measurement", "measurements", "meat", "mechanics", "media", "medicine",
  "medieval", "mediterranean", "metals", "meteorology", "mexican_cuisine", "mexican_food", "mexico", "miami",
  "michigan", "middle_ages", "milan", "military", "minerals", "mining", "missouri", "mlb",
  "mls", "models", "moldova", "monaco", "monarchs", "mongolian_empire", "montenegro", "morocco",
  "moscow", "motor_racing", "motoring", "motown", "mountains", "movies", "mozambique", "muscles",
  "museums", "music", "music_albums", "music_theory", "musical_instruments", "musicals", "musicians", "myanmar",
  "mythological_creatures", "mythology", "myths", "names", "namibia", "napoleon", "napoleonic_wars", "national_symbols",
  "native_americans", "nato", "natural_disasters", "natural_wonders", "nature", "nauru", "nautical", "nba",
  "nbl", "neighbors", "nepal", "neuroscience", "nevada", "new_jersey", "new_orleans", "new_testament",
  "new_york", "new_york_city", "new_zealand", "news", "newspapers", "nfl", "nhl", "nicaragua",
  "nicknames", "niger", "north_korea", "north_macedonia", "norway", "novel", "novels", "numbers",
  "nursery_rhymes", "nutrition", "nuts", "occupations", "oceans", "ohio", "oklahoma", "olympics",
  "oman", "one_hit_wonders", "opening_lines", "opera", "ophthalmology", "orchestra", "organisations", "organizations",
  "ottoman_empire", "outlaws", "pacific_ocean", "painting", "paintings", "pakistan", "palau", "paleontology",
  "panama", "paper_sizes", "papua_new_guinea", "paraguay", "paris", "particle_physics", "pastry", "peninsulas",
  "people", "peppers", "performers", "peru", "pharmaceuticals", "philippines", "philosophy", "photography",
  "phrases", "physics", "physiology", "piano", "pioneers", "pirates", "places", "planets",
  "plants", "play", "plays", "playwrights", "plot", "poems", "poetry", "poland",
  "political_ideology", "politics", "polynesia", "pool", "pop_music", "population", "pork", "portugal",
  "post_impressionism", "presidents", "previous_names", "primates", "print_media", "producers", "project_management", "pseudonyms",
  "psychology", "punishment", "puzzles", "qatar", "queens", "quotes", "racing", "radiation",
  "radio", "rap", "rap_music", "reality_tv", "recipes", "records", "reform", "reggae",
  "regional", "religion", "renaissance", "reptiles", "restaurants", "retail", "revolution", "revolutions",
  "rivers", "roads", "rock", "rock_and_roll", "rock_music", "romance", "romania", "romans",
  "romantic_comedies", "rome", "romeo_and_juliet", "royalty", "rugby", "rules", "russia", "rwanda",
  "sailing", "saint_kitts_and_nevis", "saint_lucia", "saint_petersburg", "saint_vincent_and_the_grenadines", "saints", "salad", "salvador_dali",
  "samoa", "san_marino", "sandwiches", "sauces", "saudi_arabia", "saxons", "sayings", "scandals",
  "scandinavia", "science", "science_fiction", "scientific_discoveries", "scotland", "scrum", "sculpture", "seafaring",
  "seafood", "seas", "seattle", "seismology", "senegal", "serbia", "seychelles", "shakespeare",
  "shapes", "sherlock_holmes", "ships", "shoes", "shopping", "siblings", "sierra_leone", "sikhism",
  "singapore", "singers", "singing", "sitcoms", "skincare", "skyscrapers", "slang", "slavery",
  "sled_dog", "slogans", "snacks", "snakes", "snooker", "so_tom_and_prncipe", "soap_operas", "soccer",
  "socialism", "society", "society_and_culture", "sociology", "software_engineering", "solomon_islands", "somalia", "songs",
  "soul_music", "sounds", "soundtracks", "soups", "south_africa", "south_america", "south_korea", "southampton",
  "southeast_asia", "soviet_union", "space", "space_exploration", "spain", "spanish", "sparkling_wine", "speeches",
  "spices", "spiders", "spirits", "spirituality", "sport", "sport_and_leisure", "spy", "sri_lanka",
  "st_louis", "stadiums", "standards", "star_trek", "star_wars", "stars", "state_capitals", "state_of_palestine",
  "statues", "stockholm", "straits", "sudan", "superfoods", "superheroes", "superman", "supernatural",
  "superstitions", "surgery", "suriname", "sushi", "sweden", "swimming", "switzerland", "sydney",
  "symbols", "taiwan", "tajikistan", "tanzania", "technology", "telecommunications", "tennis", "texas",
  "textiles", "thailand", "the_ancient_world", "the_bahamas", "the_beatles", "the_constitution", "the_crusades", "the_gambia",
  "the_human_body", "the_incas", "the_internet", "the_middle_east", "the_netherlands", "the_romans", "the_simpsons", "the_solar_system",
  "the_space_race", "the_wild_west", "theater", "theatre", "theme_parks", "thrillers", "time", "togo",
  "tonga", "tools", "totem", "tourism", "tourist_attractions", "towns", "toxicology", "toys",
  "track_and_field", "trade", "traditions", "trains", "translation", "translations", "transport", "transportation",
  "travel", "treaties", "trees", "trinidad_and_tobago", "tudor", "tunisia", "turkey", "turkmenistan",
  "tuvalu", "tv", "uganda", "uk", "ukraine", "united_arab_emirates", "united_kingdom", "united_states",
  "units", "universities", "us_history", "us_politics", "us_presidents", "us_states", "usa", "utah",
  "uzbekistan", "vampires", "vanuatu", "vatican_city", "vegetables", "venezuela", "venice", "video_games",
  "vietnam", "vietnam_war", "vikings", "virginia", "vocabulary", "volcanoes", "war", "war_of_the_roses",
  "wars", "washington_dc", "waterfalls", "weapons", "weather", "weddings", "westerns", "wine",
  "winter_sports", "wisconsin", "witchcraft", "witches", "women", "woody_allen", "words", "world_cup",
  "world_leaders", "world_war_1", "world_war_2", "world_war_ii", "writers", "writing", "wwii", "yemen",
  "young_adult", "zambia", "zimbabwe", "zodiac", "zombies", "zoology", "zulu",
];
